# Generated by Django 2.0.3 on 2019-10-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_future_student_students_user_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ('type',)},
        ),
    ]
