# Generated by Django 2.0.3 on 2019-10-11 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0004_position_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('university_name', models.CharField(blank=True, max_length=200, null=True)),
                ('university_address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('programme_title', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Position')),
                ('subject_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Subjects')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Title')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='future_student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='future_student',
            name='username',
        ),
        migrations.DeleteModel(
            name='Future_Student',
        ),
    ]
