# Generated by Django 2.0.3 on 2019-10-11 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0005_auto_20191011_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Future_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('pin_code', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('highest_degree_obtained', models.CharField(blank=True, max_length=50, null=True)),
                ('grades_obtained', models.CharField(blank=True, max_length=3, null=True)),
                ('max_grades', models.CharField(blank=True, max_length=3, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Country')),
                ('subject_interested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Subjects')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
