# Generated by Django 2.0.3 on 2019-10-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='logged_id',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='sending_id',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
