# Generated by Django 2.0.3 on 2019-10-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_future_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='future_student_post',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher_post',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
