# Generated by Django 2.0.3 on 2019-10-21 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0012_auto_20191018_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField()),
                ('position_in_company', models.CharField(blank=True, max_length=50, null=True)),
                ('website_url', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Country')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Industry')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Skills')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
