# Generated by Django 2.0.3 on 2019-10-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_studentemployeenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeestudentmapping',
            name='connected_student_user_id',
        ),
        migrations.RemoveField(
            model_name='employeestudentmapping',
            name='employee_user_id',
        ),
        migrations.RemoveField(
            model_name='studentemployeemapping',
            name='connected_employee_user_id',
        ),
        migrations.RemoveField(
            model_name='studentemployeemapping',
            name='student_user_id',
        ),
        migrations.DeleteModel(
            name='EmployeeStudentMapping',
        ),
        migrations.DeleteModel(
            name='StudentEmployeeMapping',
        ),
    ]
