# Generated by Django 2.0.3 on 2019-10-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20191022_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_post',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
