# Generated by Django 2.0.3 on 2019-10-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_teacherfuturenotifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentemployeenotification',
            name='logged_id',
        ),
        migrations.RemoveField(
            model_name='studentemployeenotification',
            name='sending_ids',
        ),
        migrations.RemoveField(
            model_name='teacherfuturenotifications',
            name='logged_id',
        ),
        migrations.RemoveField(
            model_name='teacherfuturenotifications',
            name='sending_id',
        ),
        migrations.RemoveField(
            model_name='teacherstudentnotification',
            name='logged_id',
        ),
        migrations.RemoveField(
            model_name='teacherstudentnotification',
            name='sending_ids',
        ),
        migrations.DeleteModel(
            name='StudentEmployeeNotification',
        ),
        migrations.DeleteModel(
            name='TeacherFutureNotifications',
        ),
        migrations.DeleteModel(
            name='TeacherStudentNotification',
        ),
    ]
