# Generated by Django 2.0.3 on 2019-10-24 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_futureteachermapping_teacherfuturemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureteachermapping',
            name='future_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Future_Student'),
        ),
    ]
