# Generated by Django 2.0.3 on 2019-10-24 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_auto_20191024_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherfuturemapping',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Teacher'),
        ),
    ]
